apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: product-recommendations
spec:
  image:  product-recommendations:latest
  imagePullPolicy: Never
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    kubernetes.operator.job.restart.failed: "true"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/product-recommendations.jar
    args: ["my-cluster-kafka-bootstrap.default.svc:9092", "mygroup1","/opt/flink/usrlib/productInventory.csv"]
    parallelism: 1
    upgradeMode: stateless